import React from "react";
import HeroSection from "@/presentation/components/(BLOG)/sections/HeroSection";
import RecipeLoader from "@/presentation/components/(BLOG)/recipeLoader/RecipeLoader";
import { Metadata } from "next";


export const metadata : Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
    <main className="flex flex-col min-h-screen bg-gray-100">
      <HeroSection />
      <RecipeLoader />
    </main>
  );
}

