import { Metadata } from "next"

export const metaData : Metadata = {
    title: 'Cristian\'s pastry',
    description: 'Blog di pasticceria classica e moderna',
    openGraph: {
        title: 'Cristian\'s pastry',
        description: 'Generated by create next app',
        url: 'https://cristianspastry.vercel.app/',
        siteName: 'Cristian\'s pastry',
        images: [
          {
            url: 'https://cristianspastry.vercel.app/images/logo.png',
            width: 800,
            height: 600,
          },
        ],
        locale: 'it-IT',
        type: 'website',
    },
    robots: {
        index: true,
        follow: true,
        googleBot: {
          index: true,
          follow: true,
          'max-video-preview': -1,
          'max-image-preview': 'large',
          'max-snippet': -1,
        },
    },
    twitter: {
        title: 'Cristian\'s pastry',
        card: 'summary_large_image',
    },
    icons: {
        shortcut: '/favicon.ico',
    },
    viewport: {
        width: 'device-width',
        initialScale: 1,
        maximumScale: 1,
    },
    themeColor: [
        { media: '(prefers-color-scheme: light)', color: '#fafafa' },
        { media: '(prefers-color-scheme: dark)', color: '#18181b' },
    ],
    appleWebApp: {
        title: 'Cristian\'s pastry',
        capable: true,
        statusBarStyle: 'default',
    },
}

export const routes = {
    home: '/',
    ricette: '/ricette',
    about: '/about',
    contact: '/contact',
    terminiCondizioni: '/termini-condizioni',
}

export const navLinks = [
    { label: 'Home', href: routes.home },
    { label: 'Ricette', href: routes.ricette },
    { label: 'About', href: routes.about },
    { label: 'Contact', href: routes.contact },
]

export const footerLinks = [
    { label: 'Chi siamo', href: routes.about },
    { label: 'Contatti', href: routes.contact },
    { label: 'Termini e condizioni', href: routes.terminiCondizioni },
]

export const socialLinks = [
    { label: 'Facebook', href: 'https://facebook.com', icon: 'facebook' },
    { label: 'Twitter', href: 'https://twitter.com', icon: 'twitter' },
    { label: 'Instagram', href: 'https://instagram.com', icon: 'instagram' },
    { label: 'TikTok', href: 'https://tiktok.com', icon: 'tiktok' },
]